### ISSUE TITLE
add login/signup page for user

### ISSUE THREAD

**Issue by Jefferson-Khy** [Jefferson-Khy/financial-suggestor#2]
the project currently doesnt have a way for a user to login so they can see what step they are on

**Comment by mathushabai** [comment]
I am interested in helping you with this. Could you elaborate on what information you require for the Sign Up page?

**Comment by Jefferson-Khy** [comment]
oh sorry, this is a solo project, I was just getting some practice with github features. I didn't know ppl could see the issues.
